### ISSUE TITLE
Enable multiple Components but receiving only the first one?

### ISSUE THREAD

**Issue by zaksel** [roboception/rc_genicam_api#27]
Hi there,
I observe weird behaviour, when using the command line tool to query multiple components from my rc_visard.
I get only the first Enabled component. So when Intensity is activated there is only Intensity returned. All other activated components are ignored. If disparity is the first i only get this one.

Screenshot:
![image](https://user-images.githubusercontent.com/45262936/110818818-e9d54580-828d-11eb-89aa-68a3c19884d8.png)
I expected to get Intensity, Disparity and Confidence, but got only the Intensity Image.

If i do n=100 and i'm lucky there is a disparity Image inbetween all the intensity images. I have done all Network-Optimizations and net_perf_check.sh doesn't complain about anything.

A few days ago it worked and saved all enabled images:
![image](https://user-images.githubusercontent.com/45262936/110819878-e7272000-828e-11eb-8f92-df962e7a04cd.png)

I hope somebody knows what causes this behaviour.

With kind regards
derEskimo

**Comment by heikohimu** [comment]
By default, the rc_visard sends images as soon as they are available. This means the Intensity (or IntensityCombined) images are by default send with 25 Hz. The disparity images is typically computed at a much lower rate, depending on the quality settings. Additionally, stereo matching is turned on when image streaming starts and it can take a little bit longer until the first disparity image comes.

The solution is to add the parameter to AcquisitionMultiPartMode=SynchronizedComponents to your command line. This ensures that all enabled images are always sent together, which is what you want. I think that the last time when it worked, this parameter was set on your sensor, maybe by another application or tool that was run before, because we did not change the behaviour.

**Comment by zaksel** [comment]
Thanks a lot! Didn't find this parameter.
