### ISSUE TITLE
ICommand::Execute() - wrong return type

### ISSUE THREAD

**Issue by ArsMasiuk** [roboception/rc_genicam_api#29]
ICommand::Execute() is declared as void, however it tries to return a value... see below, file ICommand.h:

/*--------------------------------------------------------*/
// ICommand
/*--------------------------------------------------------*/

//! Execute the command
virtual **void** Execute(bool Verify = true)
{
    if(ref::m_Ptr)
        **return** ref::m_Ptr->Execute(Verify);
    else
        throw ACCESS_EXCEPTION("Feature not present (reference not valid)");
}

**Comment by heikohimu** [comment]
First of all, this is part of the GenICam reference implementation which we do not support but just use as it is.
Now to your question. I agree that the code looks wrong, but it is actually valid in C++, because ref::m_Ptr->Execute(Verify) returns void. Returning void() in a void function is permitted, because these cases can happen in templates.
Does you compiler have a problem with this code?

**Comment by ArsMasiuk** [comment]
Hi and thanks for quick answer!
Sure, the code is valid for the compiler, and I have no problems with it. 
Just wanted to mention some strangeness :)
BTW maybe you know, is there a chance to get Genicam sources somewhere & compile them from the scratch?

**Comment by heikohimu** [comment]
The source code of the GenICam reference implementation is only available to group members. See https://www.emva.org/standards-technology/genicam/ for more details.

**Comment by ArsMasiuk** [comment]
I see, thank you!!
