### ISSUE TITLE
Weird result of 3D coordinates calculation

### ISSUE THREAD

**Issue by towardthesea** [roboception/rc_genicam_api#3]
Hi,
I used your `rc_genicam_api` to build my own project and followed the below guild-line to compute the 3D coordinates of a pixel from image.
![screenshot from 2018-01-24 15-53-47](https://user-images.githubusercontent.com/4939985/35338677-d6f08590-011e-11e8-98a8-bf6a688ab868.png)

From my understanding of your `sensor` and `api`, I obtained the necessary information for the calculation as:
```
        focalLength=rcg::getFloat(nodemap, "FocalLengthFactor", 0, 0, false);
        baseLine=rcg::getFloat(nodemap, "Baseline", 0, 0, true);
        dispScale=rcg::getFloat(nodemap, "Scan3dCoordinateScale", 0, 0, true);
```
and calculations were done as following:
```
        int disp = dispImg.pixel(pixel[0],pixel[1]); //this one give disparity value as the pixel
        double d = double(disp);
        point3D[0] = pixel[0]*baseLine/d;
        point3D[1] = pixel[1]*baseLine/d;
        point3D[2] = focalLength*imgW*baseLine/d;
```
However, I kept receiving weird result (depth is not sufficient right and is not corresponding to the distance to a flat object in front of the object when I moved it back and forth).

What should be wrong in my implementation/understanding?

Thanks,
Phuong

**Comment by heikohimu** [comment]
First of all, to avoid cluttering the formulas at that place in the manual, they are given by assuming that the origin of the pixel coordinate system is shifted from the left/upper corner to the center of the image. The manual explains this a few sentences below the equation, i.e.:

"Please note that equations (1) assume that the coordinate frame is centered in the middle of the image."

Secondly, although you correctly retrieved the disparity scale (dispScale), you never used it to actually scale the disparity value.

It think that the formulas in "Interfaces" / "GigE Vision 2.0/GenICam image interface" / "[Image stream conversions](http://doc.rc-visard.com/en/gigevision.html#image-stream-conversions)" make it more clear, because they give the ready to use formulas with the GenICam parameters. I will add a link in the manual from the first set of formulas to the GenICam specific ones to make this more clear.

**Comment by towardthesea** [comment]
Thanks so much for the link. It really helped!
