### ISSUE TITLE
How can i open a device by ipaddress?

### ISSUE THREAD

**Issue by cqz7927** [roboception/rc_genicam_api#39]
Usually , i know ipaddress instead of deviceid , but now i list the devices by interface and i can not get information about ipaddress by the device reference before open it , how can i get ipaddress before open device ?

**Comment by heikohimu** [comment]
Depending on the used producer, it is possible to specify an IP address instead of a device ID for discovery, i.e. 'gc_info <IP>' works.

However, the device class does not provide a method for getting the IP after discovery. The issue here is that the GenTL interface, on which rc_genicam_api is based, is an abstract, transport layer independent interface, e.g. it also works with USB3 Vision or a proprietary producer where the devices do not have an IP. It does not offer transport layer specific information.
